[package]
name = "Oxidb"
version = "0.1.0"
edition = "2024"

#[[test]]
#name = "Oxidb_tests"
#harness = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
